https://joyous-fashion-frog.cyclic.app/ketos/result

###

### cari user pake NIS 
POST https://joyous-fashion-frog.cyclic.app/student/profile
Content-Type: application/json

{
    
}


###
PUT https://joyous-fashion-frog.cyclic.app/ketos/pilih/ 
Content-Type: application/json

{
    "nis": 212210226,
    "kandidat": 10
}